version: '3.3'

services:
  wpdb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/dbdata/:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - wpdb
    image: wordpress:4.9.4-php5.6-apache
    ports:
       - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wpdb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./:/var/www/html/wp-content/plugins/wp-debug-log-plus
      - ./tmp/wp/:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=wpdb
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
    links:
      - wpdb
    ports:
      - 8080:80
    volumes:
      - /sessions
